version: '3'

services:
  db_mamboo:
    container_name: mongodb_mamboo
    image: mongo
    restart: always
    ports:
     - '27017:27017'
  api_mamboo:
    build: ./mamboo-app-back
    ports: 
     - '3001:3001'
    depends_on:
      - 'db_mamboo'
  front_mamboo:
    container_name: front_mamboo
    build: ./mamboo-front-app
    volumes: 
      - build_react:/var/www/html
  nginx_mamboo:
    container_name: nginx_mamboo
    build: ./nginx
    ports:
     - "80:80"
    volumes:
     - build_react:/var/www/html
    depends_on:
     - db_mamboo
     - api_mamboo
     - front_mamboo
volumes:
  db_mamboo:
  build_react: